# Generated by Django 3.0.6 on 2020-05-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_content',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
