# Generated by Django 3.0.6 on 2020-05-26 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200526_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='date',
        ),
        migrations.AddField(
            model_name='tasks',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2020, 5, 26, 13, 21, 15, 595308, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 26, 13, 21, 15, 595334, tzinfo=utc)),
        ),
    ]
