# Generated by Django 3.0.6 on 2020-05-26 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200526_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date_added',
            field=models.DateField(default=datetime.date(2020, 5, 26)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(default=datetime.date(2020, 5, 26)),
        ),
    ]
