# Generated by Django 3.0.6 on 2020-05-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200526_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date_added',
            field=models.DateField(default='DD/MM/YYYY'),
        ),
    ]
