# Generated by Django 3.0.6 on 2020-05-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200526_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('IN-PROGRESS', 'In progress'), ('NEW', 'New')], default='NEW', max_length=100),
        ),
    ]
