# Generated by Django 3.0.6 on 2020-05-30 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200526_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date_added',
            field=models.DateField(default=datetime.date(2020, 5, 30)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(default=datetime.date(2020, 5, 30)),
        ),
    ]
